page_manager.page.*:
  type: mapping
  label: 'Page'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Enabled status of the configuration entity'
    use_admin_theme:
      type: boolean
      label: 'Whether the page is displayed using the admin theme or not'
    langcode:
      type: string
      label: 'Default language'
    path:
      type: string
      label: 'Page path'
    display_variants:
      type: sequence
      label: 'Display variants'
      sequence:
        - type: page_manager.display_variant.[id]
          label: 'Display variant'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Access Condition'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'

page_manager.display_variant:
  type: mapping
  label: 'Display variant'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'UUID'
    selection_logic:
      type: string
      label: 'Selection logic'
    selection_conditions:
      type: sequence
      label: 'Selection Conditions'
      sequence:
        - type: condition.plugin.[id]
          label: 'Selection Condition'
    blocks:
      type: sequence
      label: 'Blocks'
      sequence:
        - type: page_manager.block_plugin.[id]

page_manager.block_plugin.*:
  type: block_settings
  mapping:
    uuid:
      type: string
      label: 'UUID'

page_manager.display_variant.block_page:
  type: page_manager.display_variant
  label: 'Block display variant'

page_manager.display_variant.http_status_code:
  type: page_manager.display_variant
  label: 'HTTP status code display variant'
  mapping:
    status_code:
      type: integer
      label: 'Status code'

# @todo Move to core.data_types.schema.yml.
condition.plugin:
  type: mapping
  label: 'Condition'
  mapping:
    id:
      type: string
      label: 'ID'
    negate:
      type: boolean
      label: 'Negate'
    uuid:
      type: string
      label: 'UUID'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        - type: string

# @todo Move to node.schema.yml.
condition.plugin.node_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        - type: string
